# fly.toml app configuration file generated for feedyouremail-staging on 2024-01-06T00:26:17-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "sjc"
console_command = "/rails/bin/rails console"

[build]

[env]
  RAILS_LOG_TO_STDOUT="true"

[deploy]
  release_command = "./bin/release"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 1024

[checks]
  [checks.rails]
    processes = ["app"]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/up"
    port = 3000
    timeout = "10s"
    type = "http"
    [checks.rails.headers]
      Host = "feedyour.email"
      X-Forwarded-Proto = "https"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[mounts]]
  source = "data"
  destination = "/rails/storage"
  initial_size = "3GB"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "20GB"
