# fly.toml app configuration file generated for feedyouremail-staging on 2024-01-06T00:26:17-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "sjc"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/release"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[mounts]
  source = "litefs"
  destination = "/data"
