# idle_timeout should be set to zero, to avoid recycling sqlite connections
# and losing the page cache
default: &default
  adapter: litedb
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  idle_timeout: 0

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  host: localhost
  database: storage/test.sqlite3

production:
  <<: *default
  database: storage/production.sqlite3
