default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: /data/feedyouremail.sqlite3

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  host: localhost
  database: storage/test.sqlite3
