default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  host: localhost
  database: storage/test.sqlite3

production:
  <<: *default
  database: storage/production.sqlite3
