default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: feedyour_email_development

test:
  <<: *default
  host: localhost
  database: feedyour_email_test
  username: rails
  password: password
