name: Renew certs
on:
  workflow_dispatch:
jobs:
  renew-cert:
    runs-on: ubuntu-latest
    env:
      GANDI_API_KEY: ${{ secrets.GANDI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
