name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up database
        run: bin/rails db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://rails:password@localhost:5432/rails_test
      - name: Run tests
        run: bin/rake
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://rails:password@localhost:5432/rails_test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Rubocop code scan
        run: bin/rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif.json
        continue-on-error: true
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        continue-on-error: true
        with:
          sarif_file: rubocop.sarif.json
          category: rubocop
      - name: Brakeman code scan
        run: bin/brakeman -q -w2 -f sarif -o brakeman.sarif.json
        continue-on-error: true
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        continue-on-error: true
        with:
          sarif_file: brakeman.sarif.json
          category: brakeman
      - name: Audit dependencies
        run: bin/bundler-audit --update
        continue-on-error: true
      - name: Lint ERB files
        run: bin/erblint --lint-all
        continue-on-error: true
      - name: Check results
        if: failure()
        run: exit 1
