name: CI

on:
  push:
    branches: [ "**", "!dependabot/**" ]
  pull_request:

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up database
        run: bin/rails db:schema:load
      - name: Run tests
        run: bin/rake assets:precompile spec
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Create results directory
        run: mkdir -p tmp/sarif
      - name: Audit dependencies
        run: bin/bundler-audit --update
        if: always()
      - name: Rubocop code scan
        id: rubocop
        run: bin/rubocop --require code_scanning --format CodeScanning::SarifFormatter -o tmp/sarif/rubocop.sarif --format clang
        if: always()
      - name: Lint ERB files
        run: bin/erb_lint --lint-all
        if: always()
      - name: Brakeman code scan
        id: brakeman
        run: bin/brakeman -q -w2 -o tmp/sarif/brakeman.sarif -o /dev/stdout --color
        if: always()
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: tmp/sarif
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl build --remote-only -e "GIT_SHA=${{ github.sha }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
