name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up database
        run: bin/rails db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://rails:password@localhost:5432/rails_test
      - name: Run tests
        run: bin/rake
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://rails:password@localhost:5432/rails_test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Audit dependencies
        run: bin/bundler-audit --update
      - name: Audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop
      - name: Lint ERB files
        run: bin/erblint --lint-all
