name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run RSpec
        run: |
          bin/rails db:create db:schema:load
          bin/rspec
        env:
          RAILS_ENV: test
          PGDATABASE: rails_test
          PGUSER: rails
          PGPASSWORD: password
