# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: indirect/test-rails@255dac821494626241316793f0c52698df9208ca
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: indirect/lint-rails@6be6f27b3f8824ec3b7e86cb238b7246be90a48b
