name: Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

permissions:
  contents: read
  deployments: write

env:
  FLY_APP: feedyouremail

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == github.event.repository.default_branch
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dentarg/fly@v1
        with:
          build-args: "GIT_SHA=${{ github.sha }}"
          fly-token: ${{ secrets.FLY_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
